version: '3.9'

services:

  db:
    image: postgres
    restart: always
    ports:
    - 5433:5432
    volumes:
    - ./pgdata:/var/lib/postgresql/data
    - ./init:/docker-entrypoint-initdb.d 

    environment:
      POSTGRES_PASSWORD: "recipesPassword"
      POSTGRES_USER: "recipesUser"
      POSTGRES_DB: "recipesDB"

